language: ruby
rvm:
  - 2.2.2
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_install:
  - openssl aes-256-cbc -K $encrypted_a82594ba762c_key -iv $encrypted_a82594ba762c_iv -in sshkeys.tar.enc -out sshkeys.tar -d
  - tar xvf sshkeys.tar
addons:
  code_climate:
    repo_token: 1a7be267094f29b00bef93c7f807ed5a5b7566092821199e80e669da5a5045c2